parameters:
#    ics_product.example.class: ICS\ProductBundle\Example

services:
#    ics_product.example:
#        class: %ics_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
